import { useEffect, useMemo, useState } from "react";
import { api } from "../services/api";

type CatalogItem={id:number;status:string;description:string};
type ReportResult={id:number;status:string;message?:string;rows:Record<string,unknown>[]};
type Health={status:string;database:string;latency_ms:number};
export default function Reports(){
 const [catalog,setCatalog]=useState<CatalogItem[]>([]),[selected,setSelected]=useState(8),[locationId,setLocationId]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[result,setResult]=useState<ReportResult|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[health,setHealth]=useState<Health|null>(null),[emailMessage,setEmailMessage]=useState("");
 useEffect(()=>{api.get<CatalogItem[]>("/reports").then(setCatalog).catch(e=>setError(e.message));api.get<Health>("/health").then(setHealth).catch(()=>setHealth(null));},[]);
 const columns=useMemo(()=>result?.rows?.[0]?Object.keys(result.rows[0]):[],[result]);
 async function run(){setLoading(true);setError("");try{const q=new URLSearchParams();if(locationId)q.set("location_id",locationId);if(start)q.set("start_date",start);if(end)q.set("end_date",end);setResult(await api.get<ReportResult>(`/reports/${selected}${q.size?`?${q}`:""}`));}catch(e){setError(e instanceof Error?e.message:"Report failed.");}finally{setLoading(false)}}
 async function emails(){setEmailMessage("");setError("");try{const data=await api.post<{generated_count:number}>("/email-logs/generate-weekly",{from_date:new Date().toISOString().slice(0,10),persist:true});setEmailMessage(`${data.generated_count} weekly email record(s) generated and logged.`);}catch(e){setError(e instanceof Error?e.message:"Email generation failed.")}}
 return <section className="report-page"><header className="report-header"><div><h1>Project Reports & Demo Tools</h1><p>Run Q8–Q19, verify the AITS connection, and demonstrate weekly email generation.</p></div><div className={`health ${health?"health--ok":"health--bad"}`}>{health?`Database connected · ${health.latency_ms} ms`:"Database unavailable"}</div></header>
 <div className="report-controls"><label>Query<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{catalog.map(x=><option key={x.id} value={x.id}>Q{x.id} · {x.status}</option>)}</select></label><label>Location ID<input value={locationId} onChange={e=>setLocationId(e.target.value)} inputMode="numeric"/></label><label>Start date<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End date<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="button button--primary" onClick={run} disabled={loading}>{loading?"Running...":"Run report"}</button><button className="button" onClick={emails}>Generate weekly emails</button></div>
 {catalog.find(x=>x.id===selected)&&<p className="report-description">{catalog.find(x=>x.id===selected)?.description}</p>}{error&&<p role="alert" className="relation-page__status relation-page__status--error">{error}</p>}{emailMessage&&<p className="relation-page__status">{emailMessage}</p>}
 {result?.message&&<p className="report-warning">{result.message}</p>}{result&&<div className="report-results"><h2>Q{result.id} Results <span>{result.rows.length} row(s)</span></h2>{result.rows.length?<div className="report-table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{result.rows.map((r,i)=><tr key={i}>{columns.map(c=><td key={c}>{r[c]==null?"—":String(r[c])}</td>)}</tr>)}</tbody></table></div>:<p>No rows returned.</p>}</div>}</section>
}
